version: '3.1'

services:
  rabbitmq_service: 
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq_service'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - main_network
  mongodb_container:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
        - main_network
  message_consumer:
    build: ./data_consumer
    restart: always
    command: python app/consumer.py
    volumes:
      - ./data_consumer/:/app
    depends_on:
      - rabbitmq_service
      - mongodb_container
    networks:
      - main_network
  main_app:
    build: ./application
    restart: always
    command: python app/main.py
    environment:
      - RABBIT_MQ_FULL_URL=amqp://guest:guest@rabbitmq_service?heartbeat=600&blocked_connection_timeout=300
    volumes:
      - ./application/:/app
    ports:
      - "8080:8080"
    expose:
      - 3000
    networks:
        - main_network
networks:
  main_network:
    driver: bridge

volumes:
  mongodb_data_container: